//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FitnessAssistant_TUZHILAVDVORYANINAV_3ISP97.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int idUser { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public System.DateTime Birthday { get; set; }
        public double Weight { get; set; }
        public double Height { get; set; }
        public Nullable<decimal> Age { get; set; }
        public int idGender { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public byte[] Photo { get; set; }
    
        public virtual Gender Gender { get; set; }
    }
}
